spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.data.mongodb.database}
      database: savor-cake
  mail:
    host: smtp.gmail.com
    port: 587
    username: dieuthuhiencb2002@gmail.com
    password: tdpn eeza gtxk sgst
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.mongodb.driver: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG